# 판다스 데이터 선택

## 열 선택하기

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('weather.csv')
df

            date  temp  max_wind  mean_wind
0     2010-08-01  28.7       8.3        3.4
1     2010-08-02  25.2       8.7        3.8
2     2010-08-03  22.1       6.3        2.9
3     2010-08-04  25.3       6.6        4.2
4     2010-08-05  27.2       9.1        5.6
...          ...   ...       ...        ...
3648  2020-07-27  22.1       4.2        1.7
3649  2020-07-28  21.9       4.5        1.6
3650  2020-07-29  21.6       3.2        1.0
3651  2020-07-30  22.9       9.7        2.4
3652  2020-07-31  25.7       4.8        2.5

[3653 rows x 4 columns]

In [3]:
df ['temp']

0       28.7
1       25.2
2       22.1
3       25.3
4       27.2
        ...
3648    22.1
3649    21.9
3650    21.6
3651    22.9
3652    25.7
Name: temp, Length: 3653, dtype: float64

### 여러 컬럼 선택하기

In [7]:
df[['date', 'temp']]

            date  temp
0     2010-08-01  28.7
1     2010-08-02  25.2
2     2010-08-03  22.1
3     2010-08-04  25.3
4     2010-08-05  27.2
...          ...   ...
3648  2020-07-27  22.1
3649  2020-07-28  21.9
3650  2020-07-29  21.6
3651  2020-07-30  22.9
3652  2020-07-31  25.7

[3653 rows x 2 columns]

## loc

- 데이터프레임명.loc[행, 열]

In [8]:
df.head()

         date  temp  max_wind  mean_wind
0  2010-08-01  28.7       8.3        3.4
1  2010-08-02  25.2       8.7        3.8
2  2010-08-03  22.1       6.3        2.9
3  2010-08-04  25.3       6.6        4.2
4  2010-08-05  27.2       9.1        5.6

In [ ]:
df.loc['temp'] # 행을 안적고 열만 적으면 오류

KeyError: 'temp'

In [10]:
df.loc[0, 'temp']

np.float64(28.7)

In [12]:
df.loc[0] # 열은 생략 가능

date         2010-08-01
temp               28.7
max_wind            8.3
mean_wind           3.4
Name: 0, dtype: object

In [14]:
df.loc[:, ['date', 'temp']] # :(콜론) 모든 행을 뜻함

            date  temp
0     2010-08-01  28.7
1     2010-08-02  25.2
2     2010-08-03  22.1
3     2010-08-04  25.3
4     2010-08-05  27.2
...          ...   ...
3648  2020-07-27  22.1
3649  2020-07-28  21.9
3650  2020-07-29  21.6
3651  2020-07-30  22.9
3652  2020-07-31  25.7

[3653 rows x 2 columns]

## iloc

- i는 정수라는 뜻
- 데이터프레임명.iloc[행번호, 열번호]

In [18]:
df.iloc[0,1]

np.float64(28.7)

In [ ]:
df.iloc[1:3] # 1,2번 행 (3번행은 포함하지 않는다.)

         date  temp  max_wind  mean_wind
1  2010-08-02  25.2       8.7        3.8
2  2010-08-03  22.1       6.3        2.9

In [20]:
df.iloc[:, 0:2]

            date  temp
0     2010-08-01  28.7
1     2010-08-02  25.2
2     2010-08-03  22.1
3     2010-08-04  25.3
4     2010-08-05  27.2
...          ...   ...
3648  2020-07-27  22.1
3649  2020-07-28  21.9
3650  2020-07-29  21.6
3651  2020-07-30  22.9
3652  2020-07-31  25.7

[3653 rows x 2 columns]

In [21]:
df.iloc[1:4, 0:3]

         date  temp  max_wind
1  2010-08-02  25.2       8.7
2  2010-08-03  22.1       6.3
3  2010-08-04  25.3       6.6

## 불(bool) 인덱싱

In [23]:
w = df['temp'] >= 30
df[w] # 참(True)인것만 행 나온다.

            date  temp  max_wind  mean_wind
1103  2013-08-08  31.3       7.8        4.6
1104  2013-08-09  30.6       9.9        6.4
1105  2013-08-10  30.6       7.4        3.8
2913  2018-07-23  30.5       6.5        1.6
2925  2018-08-04  30.3       5.8        3.0

### 조건에 맞는 데이터 추출

In [25]:
# 최고로 더웠던 날의 모든 정보(행)
w = df['temp'] == df['temp'].max()
df[w]

            date  temp  max_wind  mean_wind
1103  2013-08-08  31.3       7.8        4.6

## 조건이 2개 이상 --> 그리고 &, 또는 |

In [26]:
# 기온이 30도 이상이고, 최대풍속이 9이상인 데이터

w = (df['temp'] >= 30) & (df['max_wind'] >= 9)
df[w]

            date  temp  max_wind  mean_wind
1104  2013-08-09  30.6       9.9        6.4

In [27]:
# 기온이 30도 이상이거나, 최대풍속이 9이상인 데이터

w = (df['temp'] >= 30) | (df['max_wind'] >= 9)
df[w]

            date  temp  max_wind  mean_wind
4     2010-08-05  27.2       9.1        5.6
5     2010-08-06  26.8       9.8        8.0
6     2010-08-07  27.5       9.1        5.0
9     2010-08-10  25.6      10.2        5.5
10    2010-08-11  24.6       9.4        4.8
...          ...   ...       ...        ...
3632  2020-07-11  20.1      10.3        4.1
3634  2020-07-13  17.8      10.3        4.6
3635  2020-07-14  17.8      12.7        9.4
3641  2020-07-20  23.0      11.2        7.3
3651  2020-07-30  22.9       9.7        2.4

[1218 rows x 4 columns]

# 판다스 결측데이터 처리

## isna()  --> 값이 nan(결측치)이라면 True

In [28]:
# 최대풍속이 측정되지 않은 모든 데이터 출력

df['max_wind'].isna()

0       False
1       False
2       False
3       False
4       False
        ...
3648    False
3649    False
3650    False
3651    False
3652    False
Name: max_wind, Length: 3653, dtype: bool

In [29]:
df[df['max_wind'].isna()]

            date  temp  max_wind  mean_wind
559   2012-02-11  -0.7       NaN        NaN
560   2012-02-12   0.4       NaN        NaN
561   2012-02-13   4.0       NaN        NaN
3183  2019-04-19   7.8       NaN        2.3

## 데이터프레임명.isnull().sum()  --> 컬럼 별 결측데이터 개수

- 0 False 거짓
- 1 True 참

In [30]:
df.isnull()

       date   temp  max_wind  mean_wind
0     False  False     False      False
1     False  False     False      False
2     False  False     False      False
3     False  False     False      False
4     False  False     False      False
...     ...    ...       ...        ...
3648  False  False     False      False
3649  False  False     False      False
3650  False  False     False      False
3651  False  False     False      False
3652  False  False     False      False

[3653 rows x 4 columns]

In [31]:
df.isnull().sum()

date         0
temp         0
max_wind     4
mean_wind    6
dtype: int64

In [32]:
df.isnull().sum().sum() # 전체 데이터프레임

np.int64(10)

## 결측데이터 삭제하기 --> dropna()

In [33]:
df.dropna() # 결측치를 제거한 상태를 한번 보는 용도

            date  temp  max_wind  mean_wind
0     2010-08-01  28.7       8.3        3.4
1     2010-08-02  25.2       8.7        3.8
2     2010-08-03  22.1       6.3        2.9
3     2010-08-04  25.3       6.6        4.2
4     2010-08-05  27.2       9.1        5.6
...          ...   ...       ...        ...
3648  2020-07-27  22.1       4.2        1.7
3649  2020-07-28  21.9       4.5        1.6
3650  2020-07-29  21.6       3.2        1.0
3651  2020-07-30  22.9       9.7        2.4
3652  2020-07-31  25.7       4.8        2.5

[3646 rows x 4 columns]

In [35]:
df2 = df.dropna() # 결측치 삭제한 데이터들을 새로운 데이터프레임에 저장
df2

            date  temp  max_wind  mean_wind
0     2010-08-01  28.7       8.3        3.4
1     2010-08-02  25.2       8.7        3.8
2     2010-08-03  22.1       6.3        2.9
3     2010-08-04  25.3       6.6        4.2
4     2010-08-05  27.2       9.1        5.6
...          ...   ...       ...        ...
3648  2020-07-27  22.1       4.2        1.7
3649  2020-07-28  21.9       4.5        1.6
3650  2020-07-29  21.6       3.2        1.0
3651  2020-07-30  22.9       9.7        2.4
3652  2020-07-31  25.7       4.8        2.5

[3646 rows x 4 columns]

In [36]:
df2.isnull().sum()

date         0
temp         0
max_wind     0
mean_wind    0
dtype: int64

In [37]:
df.isnull().sum()

date         0
temp         0
max_wind     4
mean_wind    6
dtype: int64

## 결측데이터 대체하기 --> fillna()

In [38]:
df['max_wind'].isnull().sum()

np.int64(4)

In [39]:
df3 = df.copy() # 복사
df3

            date  temp  max_wind  mean_wind
0     2010-08-01  28.7       8.3        3.4
1     2010-08-02  25.2       8.7        3.8
2     2010-08-03  22.1       6.3        2.9
3     2010-08-04  25.3       6.6        4.2
4     2010-08-05  27.2       9.1        5.6
...          ...   ...       ...        ...
3648  2020-07-27  22.1       4.2        1.7
3649  2020-07-28  21.9       4.5        1.6
3650  2020-07-29  21.6       3.2        1.0
3651  2020-07-30  22.9       9.7        2.4
3652  2020-07-31  25.7       4.8        2.5

[3653 rows x 4 columns]

In [ ]:
df3 = df3.fillna(0) # 결측치를 모두 0으로 채웠다.

In [41]:
df3.isnull().sum()

date         0
temp         0
max_wind     0
mean_wind    0
dtype: int64

In [ ]:
# 평균 --> mean()
avg = df3['max_wind'].mean()
avg

np.float64(7.902436353681905)

In [45]:
df3['max_wind'] = df3['max_wind'].fillna(avg)

In [46]:
avg2 = df3['mean_wind'].mean()
avg2

np.float64(3.9299753627155765)

In [48]:
df3['mean_wind'] = df3['mean_wind'].fillna(avg2)

In [49]:
df3.tail(10)

            date  temp  max_wind  mean_wind
3643  2020-07-22  22.2       4.3        1.9
3644  2020-07-23  21.5       4.9        2.3
3645  2020-07-24  20.4       7.2        2.8
3646  2020-07-25  20.7       3.8        1.1
3647  2020-07-26  21.4       4.8        2.8
3648  2020-07-27  22.1       4.2        1.7
3649  2020-07-28  21.9       4.5        1.6
3650  2020-07-29  21.6       3.2        1.0
3651  2020-07-30  22.9       9.7        2.4
3652  2020-07-31  25.7       4.8        2.5

## 컬럼(열, 변수, 피처) 삭제 / 생성

### drop(컬럼 삭제)

In [52]:
dust = pd.read_excel('dust1.xlsx')
dust.head()

,지역,망,측정소코드,측정소명,측정일시,SO2,CO,O3,NO2,PM10,PM25,주소
0,서울 송파구,도시대기,111273,송파구,2021040101,0.004,1.0,0.002,0.066,50,18,서울 송파구 백제고분로 236
1,서울 송파구,도시대기,111273,송파구,2021040102,0.004,0.8,0.002,0.058,48,20,서울 송파구 백제고분로 236
2,서울 송파구,도시대기,111273,송파구,2021040103,0.004,0.8,0.002,0.055,44,20,서울 송파구 백제고분로 236
3,서울 송파구,도시대기,111273,송파구,2021040104,0.003,0.8,0.002,0.055,40,20,서울 송파구 백제고분로 236
4,서울 송파구,도시대기,111273,송파구,2021040105,0.004,0.8,0.002,0.053,38,17,서울 송파구 백제고분로 236

In [59]:
# 지역, 망, 측정소코드 삭제

dust = dust.drop(['지역', '망', '측정소코드'], axis=1)

In [60]:
dust.head()

,측정소명,측정일시,SO2,CO,O3,NO2,PM10,PM25,주소,city
0,송파구,2021040101,0.004,1.0,0.002,0.066,50,18,서울 송파구 백제고분로 236,서울
1,송파구,2021040102,0.004,0.8,0.002,0.058,48,20,서울 송파구 백제고분로 236,서울
2,송파구,2021040103,0.004,0.8,0.002,0.055,44,20,서울 송파구 백제고분로 236,서울
3,송파구,2021040104,0.003,0.8,0.002,0.055,40,20,서울 송파구 백제고분로 236,서울
4,송파구,2021040105,0.004,0.8,0.002,0.053,38,17,서울 송파구 백제고분로 236,서울

## 컬럼 생성하기(추가)

- 데이터프레임명[추가하고 싶은 컬럼명] = 값

In [61]:
dust['city'] = '서울'

In [62]:
dust.head()

,측정소명,측정일시,SO2,CO,O3,NO2,PM10,PM25,주소,city
0,송파구,2021040101,0.004,1.0,0.002,0.066,50,18,서울 송파구 백제고분로 236,서울
1,송파구,2021040102,0.004,0.8,0.002,0.058,48,20,서울 송파구 백제고분로 236,서울
2,송파구,2021040103,0.004,0.8,0.002,0.055,44,20,서울 송파구 백제고분로 236,서울
3,송파구,2021040104,0.003,0.8,0.002,0.055,40,20,서울 송파구 백제고분로 236,서울
4,송파구,2021040105,0.004,0.8,0.002,0.053,38,17,서울 송파구 백제고분로 236,서울

## 컬럼 이름 수정 --> rename()

- 데이터프레임명.rename(columns={'기존이름' : '새이름'})

In [64]:
dust = dust.rename(columns={
    '측정소명' : 'name', 
    '측정일시' : 'date',
    '주소' : 'addr'
})

In [65]:
dust.columns

Index(['name', 'date', 'SO2', 'CO', 'O3', 'NO2', 'PM10', 'PM25', 'addr',
       'city'],
      dtype='str')

## 데이터 형 확인 --> dtypes

In [66]:
dust.dtypes

name        str
date      int64
SO2     float64
CO      float64
O3      float64
NO2     float64
PM10      int64
PM25      int64
addr        str
city        str
dtype: object

## 데이터 형 변환 --> astype()

- 컬럼명.astype(바꿀 자료형)

In [67]:
dust['date'].astype(str)

0     2021040101
1     2021040102
2     2021040103
3     2021040104
4     2021040105
5     2021040106
6     2021040107
7     2021040108
8     2021040109
9     2021040110
10    2021040111
11    2021040112
12    2021040113
13    2021040114
14    2021040115
15    2021040116
16    2021040117
17    2021040118
18    2021040119
19    2021040120
20    2021040121
21    2021040122
22    2021040123
23    2021040124
24    2021040201
25    2021040202
26    2021040203
27    2021040204
28    2021040205
29    2021040206
30    2021040207
31    2021040208
Name: date, dtype: str

In [68]:
dust['date'] = dust['date'].astype(str)

In [69]:
dust.dtypes

name        str
date        str
SO2     float64
CO      float64
O3      float64
NO2     float64
PM10      int64
PM25      int64
addr        str
city        str
dtype: object

In [70]:
# 첫 8자리만 자른다. --> slice()
dust['date'] = dust['date'].str.slice(0,8)

## to_datetime() --> 날짜 / 시간 형으로 변환 (시계열)

In [72]:
pd.to_datetime(dust['date'])

0    2021-04-01
1    2021-04-01
2    2021-04-01
3    2021-04-01
4    2021-04-01
5    2021-04-01
6    2021-04-01
7    2021-04-01
8    2021-04-01
9    2021-04-01
10   2021-04-01
11   2021-04-01
12   2021-04-01
13   2021-04-01
14   2021-04-01
15   2021-04-01
16   2021-04-01
17   2021-04-01
18   2021-04-01
19   2021-04-01
20   2021-04-01
21   2021-04-01
22   2021-04-01
23   2021-04-01
24   2021-04-02
25   2021-04-02
26   2021-04-02
27   2021-04-02
28   2021-04-02
29   2021-04-02
30   2021-04-02
31   2021-04-02
Name: date, dtype: datetime64[us]

In [73]:
dust['date'] = pd.to_datetime(dust['date'])
dust.dtypes

name               str
date    datetime64[us]
SO2            float64
CO             float64
O3             float64
NO2            float64
PM10             int64
PM25             int64
addr               str
city               str
dtype: object