In [25]:
# 라이브러리 불러오기

import pandas as pd
import numpy as np

In [4]:
dust = pd.read_excel('dust1.xlsx')
dust.head()

,지역,망,측정소코드,측정소명,측정일시,SO2,CO,O3,NO2,PM10,PM25,주소
0,서울 송파구,도시대기,111273,송파구,2021040101,0.004,1.0,0.002,0.066,50,18,서울 송파구 백제고분로 236
1,서울 송파구,도시대기,111273,송파구,2021040102,0.004,0.8,0.002,0.058,48,20,서울 송파구 백제고분로 236
2,서울 송파구,도시대기,111273,송파구,2021040103,0.004,0.8,0.002,0.055,44,20,서울 송파구 백제고분로 236
3,서울 송파구,도시대기,111273,송파구,2021040104,0.003,0.8,0.002,0.055,40,20,서울 송파구 백제고분로 236
4,서울 송파구,도시대기,111273,송파구,2021040105,0.004,0.8,0.002,0.053,38,17,서울 송파구 백제고분로 236

In [5]:
# 컬럼 이름 변경

dust = dust.rename(columns={'측정일시':'date'})
dust.head()

,지역,망,측정소코드,측정소명,date,SO2,CO,O3,NO2,PM10,PM25,주소
0,서울 송파구,도시대기,111273,송파구,2021040101,0.004,1.0,0.002,0.066,50,18,서울 송파구 백제고분로 236
1,서울 송파구,도시대기,111273,송파구,2021040102,0.004,0.8,0.002,0.058,48,20,서울 송파구 백제고분로 236
2,서울 송파구,도시대기,111273,송파구,2021040103,0.004,0.8,0.002,0.055,44,20,서울 송파구 백제고분로 236
3,서울 송파구,도시대기,111273,송파구,2021040104,0.003,0.8,0.002,0.055,40,20,서울 송파구 백제고분로 236
4,서울 송파구,도시대기,111273,송파구,2021040105,0.004,0.8,0.002,0.053,38,17,서울 송파구 백제고분로 236

In [6]:
# 자료형 확인

dust.dtypes

지역           str
망            str
측정소코드      int64
측정소명         str
date       int64
SO2      float64
CO       float64
O3       float64
NO2      float64
PM10       int64
PM25       int64
주소           str
dtype: object

In [7]:
# 문자열로 형 변환

dust['date'] = dust['date'].astype(str)
dust['date'] = dust['date'].str.slice(0, 8)
dust.dtypes

지역           str
망            str
측정소코드      int64
측정소명         str
date         str
SO2      float64
CO       float64
O3       float64
NO2      float64
PM10       int64
PM25       int64
주소           str
dtype: object

In [8]:
# 날짜형으로 형 변환

dust['date'] = pd.to_datetime(dust['date'])
dust.dtypes

지역                  str
망                   str
측정소코드             int64
측정소명                str
date     datetime64[us]
SO2             float64
CO              float64
O3              float64
NO2             float64
PM10              int64
PM25              int64
주소                  str
dtype: object

# 날자형을 년, 월, 일로 분리 추출

In [9]:
# dt 속성

dust['date'].dt

In [ ]:
dust['date'].dt.year # 연도 추출

0     2021
1     2021
2     2021
3     2021
4     2021
5     2021
6     2021
7     2021
8     2021
9     2021
10    2021
11    2021
12    2021
13    2021
14    2021
15    2021
16    2021
17    2021
18    2021
19    2021
20    2021
21    2021
22    2021
23    2021
24    2021
25    2021
26    2021
27    2021
28    2021
29    2021
30    2021
31    2021
Name: date, dtype: int32

## 년, 월, 일 컬럼을 생성

In [12]:
dust['year'] = dust['date'].dt.year # 연도 추출
dust['month'] = dust['date'].dt.month # 월 추출
dust['day'] = dust['date'].dt.day # 일 추출

In [13]:
dust.head()

,지역,망,측정소코드,측정소명,date,SO2,CO,O3,NO2,PM10,PM25,주소,year,month,day
0,서울 송파구,도시대기,111273,송파구,2021-04-01,0.004,1.0,0.002,0.066,50,18,서울 송파구 백제고분로 236,2021,4,1
1,서울 송파구,도시대기,111273,송파구,2021-04-01,0.004,0.8,0.002,0.058,48,20,서울 송파구 백제고분로 236,2021,4,1
2,서울 송파구,도시대기,111273,송파구,2021-04-01,0.004,0.8,0.002,0.055,44,20,서울 송파구 백제고분로 236,2021,4,1
3,서울 송파구,도시대기,111273,송파구,2021-04-01,0.003,0.8,0.002,0.055,40,20,서울 송파구 백제고분로 236,2021,4,1
4,서울 송파구,도시대기,111273,송파구,2021-04-01,0.004,0.8,0.002,0.053,38,17,서울 송파구 백제고분로 236,2021,4,1

# 데이터 병합

In [14]:
s1 = pd.read_excel('nation.xlsx')
s2 = pd.read_excel('code.xlsx')

In [15]:
s1.head(2)

  국적코드  성별    입국객수    증가수
0  A01  남성  125000   8000
1  A01  여성  130000  10000

In [16]:
s2.head(2)

  국적코드  국적명
0  A01  필리핀
1  A02   일본

## pd.merge() 함수

- pd.merge(데이터프레임1, 데이터프레임2, on=기준컬럼명, how='inner')
- how에는 'outer', 'left', 'right' 도 가능

In [17]:
# 국적 코드 컬럼 기준

pd.merge(s1, s2, on='국적코드')

  국적코드  성별    입국객수    증가수  국적명
0  A01  남성  125000   8000  필리핀
1  A01  여성  130000  10000  필리핀
2  A05  남성     300     10   호주
3  A05  여성     200     50   호주
4  A06  남성  158912  24486  베트남
5  A06  여성  325000  63466  베트남

In [18]:
# 오른쪽 컬럼 기준 (ex.차집합)

pd.merge(s1, s2, how='right', on='국적코드')

   국적코드   성별      입국객수      증가수  국적명
0   A01   남성  125000.0   8000.0  필리핀
1   A01   여성  130000.0  10000.0  필리핀
2   A02  NaN       NaN      NaN   일본
3   A03  NaN       NaN      NaN   미국
4   A04  NaN       NaN      NaN   중국
5   A05   남성     300.0     10.0   호주
6   A05   여성     200.0     50.0   호주
7   A06   남성  158912.0  24486.0  베트남
8   A06   여성  325000.0  63466.0  베트남
9   A07  NaN       NaN      NaN  스위스
10  A99  NaN       NaN      NaN   기타

# 데이터 그룹핑

## groupby()

In [21]:
# 국적코드별 성별, 입국객 수, 증가수
s1.groupby('국적코드').sum()

        성별    입국객수    증가수
국적코드
A01   남성여성  255000  18000
A05   남성여성     500     60
A06   남성여성  483912  87952

In [23]:
# 국적코드별, 성별 --> 입국객 수, 증가수
# 그룹을 2개
s1.groupby(['국적코드', '성별']).sum()

           입국객수    증가수
국적코드 성별
A01  남성  125000   8000
     여성  130000  10000
A05  남성     300     10
     여성     200     50
A06  남성  158912  24486
     여성  325000  63466